### PR TITLE
Create fr.yml

### PR DESCRIPTION
**Pull request by AFGAME**
Voici la traduction complète de biomes en français.

### CODE REVIEW

**Comment by tastybento** [comment]
@Poslovitch Est-ce que c'est bon?

**Comment by Poslovitch** [comment]
There is room to improve, but it's a good starting point nonetheless.

**Comment by AFGAME** [comment]
Sorry if all is not good I did it as I thought

**Comment by Poslovitch** [comment]
Now that it's in place, you could start working on it on GitLocalize if you find things to change 😉

**Comment by AFGAME** [comment]
The version I sent is on gitlocalize

**Comment by tastybento** [comment]
@AFGAME Please use this link: https://gitlocalize.com/repo/2894/fr/src/main/resources/locales/en-US.yml
Thank you for your support!

**Pull request merged**
